export const FETCH_STATES_SUCCESS = "FETCH_COUNTRIES";
export const FETCH_STATES_REQUEST = "REQUEST_COUNTRIES";
export const FETCH_STATES_ERROR = "FETCH_COUNTRIES_ERROR";
export const SET_HIDE_COLUMNS_STATES = "HIDE_COLUMNS";
export const SET_SORT_STATES = "SORT_COUNTRIES";
export const SET_HEADER_DATA_STATES = "SET_HEADER_DATA";
export const SET_FILTER_VALUE_STATES = "SET_FILTER_VALUE";
export const RESET_STATES = "RESET_COUNTRIES";
