export const SET_COUNTRIES = "SET_COUNTRIES ";
export const FETCH_COUNTRIES_SUCCESS = "FETCH_COUNTRIES";
export const FETCH_COUNTRIES_REQUEST = "REQUEST_COUNTRIES";
export const FETCH_COUNTRIES_ERROR = "FETCH_COUNTRIES_ERROR";
